# Generated by Django 5.2.15 on 2026-06-28 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_date_joined_alter_user_username"),
        (
            "congress",
            "0003_rename_congress_rep_chamber_7b2a0b_idx_congress_re_chamber_211ef4_idx_and_more",
        ),
        (
            "legislation",
            "0003_rename_legislation__updated_7c8e1a_idx_legislation_updated_dd9aeb_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_by_users",
                        to="legislation.bill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_trackedbill",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_tr_user_id_8be280_idx",
                    ),
                    models.Index(
                        fields=["bill"], name="accounts_tr_bill_id_df969c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "bill"),
                        name="accounts_trackedbill_user_bill_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackedLegislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "representative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_by_users",
                        to="congress.representative",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_legislators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_trackedlegislator",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_tr_user_id_307bfe_idx",
                    ),
                    models.Index(
                        fields=["representative"], name="accounts_tr_represe_ab1798_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "representative"),
                        name="accounts_trackedlegislator_user_rep_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackedTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_by_users",
                        to="legislation.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_trackedtopic",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_tr_user_id_923e3d_idx",
                    ),
                    models.Index(
                        fields=["topic"], name="accounts_tr_topic_i_e15a0f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "topic"),
                        name="accounts_trackedtopic_user_topic_uniq",
                    )
                ],
            },
        ),
    ]
