# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations


def copy_followed_topics_to_tracking(apps, schema_editor):
    UserPreference = apps.get_model("accounts", "UserPreference")
    TrackedTopic = apps.get_model("accounts", "TrackedTopic")
    for preference in UserPreference.objects.filter(topic__isnull=False).iterator():
        TrackedTopic.objects.get_or_create(
            user_id=preference.user_id,
            topic_id=preference.topic_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_trackedbill_trackedlegislator_trackedtopic"),
    ]

    operations = [
        migrations.RunPython(
            copy_followed_topics_to_tracking,
            migrations.RunPython.noop,
        ),
    ]
