# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_migrate_followed_topics_to_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="topic",
        ),
    ]
