# Generated by Django 5.2 on 2026-08-21

# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_userpreference_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="openai", max_length=32)),
                ("encrypted_envelope", models.TextField()),
                ("key_suffix", models.CharField(max_length=4)),
                ("encryption_key_id", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                (
                    "validated_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "validated_provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "validated_model",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "accounts_llmcredential"},
        ),
    ]
