# Generated by Django 4.2.29 on 2026-03-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legislation", "0002_bill_latest_contract"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bill",
            new_name="legislation_updated_dd9aeb_idx",
            old_name="legislation__updated_7c8e1a_idx",
        ),
        migrations.RenameIndex(
            model_name="bill",
            new_name="legislation_process_b0cf52_idx",
            old_name="legislation__process_2b4f1c_idx",
        ),
        migrations.RenameIndex(
            model_name="billcontract",
            new_name="legislation_bill_id_69fa26_idx",
            old_name="legislation__bill_id_1a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="billcontract",
            new_name="legislation_contrac_e0d34d_idx",
            old_name="legislation__contract_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="billcontract",
            new_name="legislation_bill_id_f02bda_idx",
            old_name="legislation__bill_id_7e8f0a_idx",
        ),
        migrations.RenameIndex(
            model_name="billdocument",
            new_name="legislation_bill_id_776d55_idx",
            old_name="legislation__bill_id_9a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="billdocument",
            new_name="legislation_version_9394c5_idx",
            old_name="legislation__version_4d5e6f_idx",
        ),
        migrations.RenameIndex(
            model_name="billdocument",
            new_name="legislation_bill_id_13d987_idx",
            old_name="legislation__bill_id_7e8f9a_idx",
        ),
        migrations.RenameIndex(
            model_name="billsimilarity",
            new_name="legislation_bill_a__a4136d_idx",
            old_name="legislation__bill_a_7e8f9a_idx",
        ),
        migrations.RenameIndex(
            model_name="billsimilarity",
            new_name="legislation_bill_b__e5536c_idx",
            old_name="legislation__bill_b_0a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="billsimilarity",
            new_name="legislation_similar_183d43_idx",
            old_name="legislation__similari_3d4e5f_idx",
        ),
        migrations.RenameIndex(
            model_name="billtopic",
            new_name="legislation_topic_i_197c59_idx",
            old_name="legislation__topic_i_8a9b0c_idx",
        ),
        migrations.RenameIndex(
            model_name="billtopic",
            new_name="legislation_bill_id_c89bc1_idx",
            old_name="legislation__bill_id_1d2e3f_idx",
        ),
        migrations.RenameIndex(
            model_name="billtopic",
            new_name="legislation_topic_i_df97d4_idx",
            old_name="legislation__topic_i_4a5b6c_idx",
        ),
        migrations.RenameIndex(
            model_name="evidencespan",
            new_name="legislation_contrac_63511f_idx",
            old_name="legislation__contract_1b2c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="evidencespan",
            new_name="legislation_bill_id_cfdfa3_idx",
            old_name="legislation__bill_id_4e5f6a_idx",
        ),
    ]
