# Generated by Django 5.2.12 on 2026-04-21 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "legislation",
            "0003_rename_legislation__updated_7c8e1a_idx_legislation_updated_dd9aeb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billcontract",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="legislation.billdocument",
            ),
        ),
        migrations.AlterField(
            model_name="evidencespan",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_spans",
                to="legislation.billdocument",
            ),
        ),
    ]
