# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


def remove_duplicate_contracts_and_topics(apps, schema_editor):
    Bill = apps.get_model("legislation", "Bill")
    BillContract = apps.get_model("legislation", "BillContract")
    BillTopic = apps.get_model("legislation", "BillTopic")

    seen_contracts = {}
    for contract in BillContract.objects.order_by("-id").iterator():
        key = (
            "document",
            contract.document_id,
            contract.contract_hash,
        ) if contract.document_id else (
            "metadata",
            contract.bill_id,
            contract.contract_hash,
        )
        kept = seen_contracts.get(key)
        if kept is None:
            seen_contracts[key] = contract.id
            continue
        Bill.objects.filter(latest_contract_id=contract.id).update(
            latest_contract_id=kept
        )
        contract.delete()

    seen_topics = set()
    for bill_topic in BillTopic.objects.order_by("-id").iterator():
        key = (bill_topic.bill_id, bill_topic.topic_id)
        if key in seen_topics:
            bill_topic.delete()
        else:
            seen_topics.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("legislation", "0004_make_document_nullable"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_contracts_and_topics,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="billcontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("document", "contract_hash"),
                name="legislation_contract_document_hash_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="billcontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", True)),
                fields=("bill", "contract_hash"),
                name="legislation_metadata_contract_hash_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="billtopic",
            constraint=models.UniqueConstraint(
                fields=("bill", "topic"),
                name="legislation_billtopic_bill_topic_uniq",
            ),
        ),
    ]
