# Generated by Django 5.2.17 on 2026-08-21

# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_llmcredential"),
        ("legislation", "0006_remove_bill_unpopulated_document_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillEnhancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("requested_model", models.CharField(max_length=128)),
                ("reasoning_effort", models.CharField(max_length=16)),
                ("prompt_version", models.CharField(max_length=32)),
                ("output_schema_version", models.CharField(max_length=32)),
                ("source_packet_version", models.CharField(max_length=32)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("source_manifest_json", models.JSONField(default=dict)),
                ("source_snapshot_json", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_enhancements",
                        to="legislation.bill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_enhancements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "legislation_billenhancement"},
        ),
        migrations.CreateModel(
            name="BillEnhancementAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("credential_revision", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                            ("outcome_unknown", "Outcome unknown"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                (
                    "dispatch_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "dispatch_lease_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("run_token", models.CharField(blank=True, default="", max_length=64)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_input_tokens", models.PositiveIntegerField()),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "provider_response_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "resolved_model",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("result_json", models.JSONField(blank=True, null=True)),
                (
                    "failure_category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enhancement_attempts",
                        to="accounts.llmcredential",
                    ),
                ),
                (
                    "enhancement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="legislation.billenhancement",
                    ),
                ),
            ],
            options={"db_table": "legislation_billenhancementattempt"},
        ),
        migrations.AddField(
            model_name="billenhancement",
            name="successful_attempt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_enhancement",
                to="legislation.billenhancementattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancementattempt",
            index=models.Index(
                fields=["status", "available_at"], name="legislation_status_b7b70e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancementattempt",
            index=models.Index(
                fields=["status", "dispatch_lease_expires_at"],
                name="legislation_status_80fd0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancementattempt",
            index=models.Index(
                fields=["status", "lease_expires_at"],
                name="legislation_status_b44a22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancementattempt",
            index=models.Index(
                fields=["enhancement", "created_at"],
                name="legislation_enhance_e02873_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billenhancementattempt",
            constraint=models.UniqueConstraint(
                fields=("enhancement", "sequence"),
                name="legislation_enhancement_attempt_sequence_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="billenhancementattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "running"])),
                fields=("enhancement",),
                name="legislation_enhancement_one_active_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancement",
            index=models.Index(
                fields=["user", "bill", "-created_at"],
                name="legislation_user_id_559b8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billenhancement",
            index=models.Index(
                fields=["bill", "request_fingerprint"],
                name="legislation_bill_id_516c3f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billenhancement",
            constraint=models.UniqueConstraint(
                fields=("user", "bill", "request_fingerprint"),
                name="legislation_enhancement_request_uniq",
            ),
        ),
    ]
