"""
Canonical topic taxonomy for legislation classification.

Each topic has keywords matched against bill title, summary, and contract_json
fields. Keywords are lowercased at match time. Order matters only for display;
a bill can match multiple topics.
"""

TOPICS = [
    {
        "name": "Agriculture & Food",
        "slug": "agriculture-food",
        "description": "Farming, food safety, USDA programs, crop insurance, nutrition assistance.",
        "keywords": [
            "agriculture", "farm", "farming", "crop", "livestock", "usda",
            "food safety", "food supply", "nutrition", "snap", "food stamp",
            "rural development", "irrigation", "pesticide", "fertilizer",
            "dairy", "grain", "commodity", "ranching", "ranch",
            "poultry", "meat", "seafood", "organic", "herbicide",
            "harvest", "arable", "agribusiness", "horticulture",
            "food labeling", "grocery", "hunger", "famine",
            "agricultural", "wic", "school lunch", "school meal",
        ],
    },
    {
        "name": "Armed Forces & National Security",
        "slug": "armed-forces-national-security",
        "description": "Military, defense spending, veterans, national security, intelligence.",
        "keywords": [
            "military", "defense", "armed forces", "veteran", "pentagon",
            "national security", "intelligence", "dod", "department of defense",
            "army", "navy", "air force", "marine", "coast guard",
            "national guard", "cyber security", "cybersecurity", "missile",
            "nuclear weapon", "terrorism", "counterterrorism", "nato",
            "warfare", "deployment", "troops", "soldier", "servicemember",
            "service member", "combat", "munitions", "weapons",
            "military base", "fort", "warfighter", "espionage",
            "classified", "top secret", "homeland security", "dhs",
            "cia", "nsa", "special forces", "draft",
        ],
    },
    {
        "name": "Budget & Taxation",
        "slug": "budget-taxation",
        "description": "Federal budget, appropriations, tax policy, IRS, national debt.",
        "keywords": [
            "budget", "appropriation", "tax", "taxation", "irs",
            "internal revenue", "fiscal", "deficit", "national debt",
            "debt ceiling", "spending", "revenue", "tariff", "duty",
            "excise", "income tax", "corporate tax", "tax credit",
            "tax deduction", "tax reform", "taxpayer", "withholding",
            "appropriations", "sequester", "sequestration",
            "government shutdown", "continuing resolution", "omnibus",
            "tax exempt", "tax-exempt", "deductible",
        ],
    },
    {
        "name": "Civil Rights & Liberties",
        "slug": "civil-rights-liberties",
        "description": "Discrimination, voting rights, privacy, free speech, equal protection.",
        "keywords": [
            "civil rights", "civil liberties", "discrimination",
            "equal protection", "voting rights", "free speech",
            "freedom of speech", "privacy", "due process", "segregation",
            "hate crime", "racial justice", "lgbtq", "disability rights",
            "americans with disabilities", "title vi", "title ix",
            "equality", "bias", "prejudice", "affirmative action",
            "voter suppression", "gerrymandering", "redistricting",
            "first amendment", "second amendment", "fourth amendment",
            "religious freedom", "religious liberty",
            "election", "ballot", "poll", "voter", "vote",
            "census", "reapportionment",
        ],
    },
    {
        "name": "Commerce & Trade",
        "slug": "commerce-trade",
        "description": "International trade, tariffs, small business, consumer protection, FTC.",
        "keywords": [
            "commerce", "trade", "tariff", "import", "export",
            "small business", "sba", "consumer protection", "ftc",
            "federal trade commission", "antitrust", "competition",
            "intellectual property", "patent", "trademark", "copyright",
            "e-commerce", "supply chain", "merchant", "manufacturer",
            "manufacturing", "franchise", "retail", "wholesale",
            "marketplace", "vendor",
        ],
    },
    {
        "name": "Crime & Law Enforcement",
        "slug": "crime-law-enforcement",
        "description": "Criminal justice, FBI, DOJ, policing, sentencing, prisons.",
        "keywords": [
            "crime", "criminal", "law enforcement", "police", "policing",
            "fbi", "doj", "department of justice", "prison", "incarceration",
            "sentencing", "probation", "parole", "drug trafficking",
            "organized crime", "gun violence", "firearm", "gun control",
            "background check", "forensic", "trafficking", "traffick",
            "homicide", "murder", "assault", "robbery", "theft",
            "fraud", "corruption", "bribery", "extortion",
            "smuggling", "cartel", "gang", "felony", "misdemeanor",
            "prosecution", "prosecutor", "conviction", "recidivism",
            "death penalty", "bail", "warrant", "domestic violence",
            "sexual assault", "stalking", "victim", "restitution",
            "child exploitation", "child abuse", "nitrous oxide",
            "fentanyl", "overdose", "illegal drug", "controlled substance",
            "drug offense", "narcotics", "dea",
        ],
    },
    {
        "name": "Economy & Finance",
        "slug": "economy-finance",
        "description": "Banking, financial regulation, SEC, Federal Reserve, housing market.",
        "keywords": [
            "economy", "economic", "financial", "banking", "bank",
            "sec", "securities", "federal reserve", "wall street",
            "stock market", "cryptocurrency", "fintech", "mortgage",
            "loan", "credit", "inflation", "recession", "gdp",
            "monetary policy", "interest rate", "investor", "investment",
            "hedge fund", "mutual fund", "bond", "treasury",
            "bankruptcy", "insolvency",
            "fdic", "credit union",
        ],
    },
    {
        "name": "Education",
        "slug": "education",
        "description": "K-12, higher education, student loans, STEM, school funding.",
        "keywords": [
            "education", "school", "university", "college", "student",
            "student loan", "student debt", "pell grant", "scholarship",
            "teacher", "curriculum", "stem", "higher education",
            "k-12", "head start", "special education", "charter school",
            "vocational", "workforce training", "classroom", "tuition",
            "graduate", "undergraduate", "diploma", "degree",
            "literacy", "library", "academic", "professor",
            "campus", "sorority", "fraternity", "title iv",
        ],
    },
    {
        "name": "Energy",
        "slug": "energy",
        "description": "Oil, gas, renewable energy, nuclear, grid, DOE programs.",
        "keywords": [
            "energy", "oil", "gas", "petroleum", "renewable",
            "solar", "wind energy", "nuclear energy", "hydroelectric",
            "natural gas", "fossil fuel", "electric grid", "power grid",
            "doe", "department of energy", "pipeline", "fracking",
            "clean energy", "energy efficiency", "battery",
            "electricity", "utility", "blackout", "brownout",
            "turbine", "generator", "fuel", "ethanol", "biofuel",
            "geothermal", "hydrogen", "power plant", "refinery",
            "drilling", "offshore drilling",
        ],
    },
    {
        "name": "Environment & Climate",
        "slug": "environment-climate",
        "description": "EPA, climate change, pollution, conservation, endangered species.",
        "keywords": [
            "environment", "environmental", "climate", "climate change",
            "global warming", "epa", "pollution", "emission", "carbon",
            "greenhouse", "conservation", "endangered species", "wildlife",
            "clean air", "clean water", "superfund", "toxic",
            "deforestation", "biodiversity", "wetland", "ecosystem",
            "recycling", "waste", "landfill", "contamination",
            "habitat", "ozone", "smog", "particulate",
            "chemical", "pfas", "kelp", "marine", "coral",
            "wildfire", "wildland", "fire recovery", "flood",
            "drought", "erosion", "estuary", "estuaries",
        ],
    },
    {
        "name": "Foreign Affairs",
        "slug": "foreign-affairs",
        "description": "Diplomacy, sanctions, foreign aid, State Department, treaties.",
        "keywords": [
            "foreign affairs", "foreign policy", "diplomacy", "diplomat",
            "ambassador", "state department", "sanction", "foreign aid",
            "treaty", "international relations", "united nations",
            "human rights", "refugee", "asylum", "genocide",
            "arms control", "embassy", "consulate", "extradition",
            "sovereignty", "international law", "war crimes",
            "peacekeeping", "coalition", "alliance",
            "iran", "china", "russia", "north korea", "ukraine",
            "israel", "taiwan", "cuba", "venezuela",
            "dictator", "regime", "authoritarian",
        ],
    },
    {
        "name": "Government Operations",
        "slug": "government-operations",
        "description": "Federal agencies, government reform, oversight, FOIA, procurement.",
        "keywords": [
            "government operations", "federal agency", "government reform",
            "oversight", "inspector general", "foia",
            "freedom of information", "procurement", "gsa",
            "general services", "federal employee", "civil service",
            "government accountability", "gao", "regulatory reform",
            "bureaucracy", "executive order", "government shutdown",
            "federal workforce", "transparency", "whistleblower",
            "accountability", "audit", "compliance",
            "rulemaking", "interagency",
        ],
    },
    {
        "name": "Health",
        "slug": "health",
        "description": "Healthcare, Medicare, Medicaid, FDA, public health, mental health.",
        "keywords": [
            "health", "healthcare", "health care", "medicare", "medicaid",
            "fda", "public health", "mental health", "opioid",
            "drug pricing", "prescription drug", "pharmaceutical",
            "hospital", "insurance", "affordable care", "aca",
            "pandemic", "vaccine", "cdc", "nih", "biomedical",
            "telehealth", "substance abuse", "addiction", "rehab",
            "rehabilitation", "therapy", "therapeutic", "clinical",
            "diagnosis", "disease", "cancer", "diabetes", "alzheimer",
            "overdose", "fentanyl", "physician",
            "nurse", "nursing", "surgeon", "medical", "medicine",
            "wellness", "screening", "immunization",
            "epinephrine", "epipen", "allergy", "syndrome",
            "disorder", "dental", "vision", "hearing", "organ",
            "transplant", "blood", "rare disease", "clinical trial",
            "drug safety", "pharmacy", "pharmacist", "dosage",
            "carcinoma", "tumor", "als", "autism", "epilepsy",
            "asthma", "obesity", "stroke", "dementia", "parkinsons",
            "hiv", "aids", "hepatitis", "tuberculosis", "malaria",
            "maternal", "prenatal", "postnatal", "infant", "neonatal",
            "hospice", "palliative", "prosthetic", "prosthesis",
            "bio-data", "biodata",
        ],
    },
    {
        "name": "Housing & Urban Development",
        "slug": "housing-urban-development",
        "description": "Affordable housing, HUD, homelessness, zoning, rental assistance.",
        "keywords": [
            "housing", "affordable housing", "hud", "homelessness",
            "homeless", "rental", "rent", "mortgage", "zoning",
            "public housing", "section 8", "urban development",
            "community development", "fair housing", "tenant",
            "landlord", "eviction", "shelter", "dwelling",
            "apartment", "condominium", "residential",
        ],
    },
    {
        "name": "Immigration",
        "slug": "immigration",
        "description": "Border security, visas, citizenship, DACA, deportation, refugees.",
        "keywords": [
            "immigration", "immigrant", "border", "border security",
            "visa", "citizenship", "naturalization", "daca", "dreamer",
            "deportation", "asylum", "refugee", "green card",
            "undocumented", "ice", "customs and border",
            "immigration reform", "work permit", "h-1b",
            "migration", "migrant", "alien", "noncitizen",
            "passport", "uscis", "temporary protected",
            "consular",
        ],
    },
    {
        "name": "Infrastructure & Transportation",
        "slug": "infrastructure-transportation",
        "description": "Roads, bridges, transit, FAA, railroads, broadband, water systems.",
        "keywords": [
            "infrastructure", "transportation", "highway", "road",
            "bridge", "transit", "railroad", "rail", "amtrak",
            "aviation", "faa", "airport", "port", "shipping",
            "broadband", "internet access", "water infrastructure",
            "dam", "public works", "dot", "department of transportation",
            "trucking", "truck", "freight", "cargo", "vehicle",
            "automobile", "traffic", "commute", "ferry",
            "pipeline", "tunnel", "interchange",
        ],
    },
    {
        "name": "Labor & Employment",
        "slug": "labor-employment",
        "description": "Wages, unions, OSHA, unemployment, workplace safety, pensions.",
        "keywords": [
            "labor", "employment", "worker", "wage", "minimum wage",
            "union", "collective bargaining", "osha", "workplace safety",
            "unemployment", "pension", "retirement", "401k",
            "paid leave", "family leave", "overtime", "gig economy",
            "workforce", "hiring", "layoff", "termination",
            "workplace", "employer", "employee",
            "apprentice", "apprenticeship",
            "equal pay",
        ],
    },
    {
        "name": "Native Americans",
        "slug": "native-americans",
        "description": "Tribal sovereignty, Indian affairs, Bureau of Indian Affairs, reservations.",
        "keywords": [
            "native american", "tribal", "tribe", "indian affairs",
            "bureau of indian affairs", "reservation", "indigenous",
            "alaska native", "native hawaiian", "tribal sovereignty",
            "hawai'i", "hawaii", "pueblo", "navajo", "cherokee",
        ],
    },
    {
        "name": "Public Lands & Natural Resources",
        "slug": "public-lands-natural-resources",
        "description": "National parks, BLM, forestry, mining, water rights, fisheries.",
        "keywords": [
            "public land", "national park", "blm", "bureau of land",
            "forestry", "forest service", "mining", "mineral",
            "water rights", "fishery", "fishing", "ocean", "coastal",
            "wilderness", "monument", "recreation",             "cemetery", "cemeteries",
            "national forest", "national monument", "trail",
            "river", "lake", "mountain", "canyon", "desert",
            "land management", "grazing", "timber",
            "disposal", "surplus land",
        ],
    },
    {
        "name": "Science & Technology",
        "slug": "science-technology",
        "description": "NASA, NSF, AI, research funding, data privacy, telecommunications.",
        "keywords": [
            "science", "technology", "nasa", "nsf", "research",
            "artificial intelligence", "machine learning",
            "data privacy", "telecommunications", "5g", "space",
            "satellite", "quantum", "biotech", "biotechnology",
            "innovation", "r&d", "nist", "algorithm", "software",
            "cyber", "digital", "computing", "robotics",
            "autonomous", "drone", "genome", "genetic",
            "nanotechnology", "spectrum",
        ],
    },
    {
        "name": "Social Services & Welfare",
        "slug": "social-services-welfare",
        "description": "Social Security, disability, child welfare, poverty programs.",
        "keywords": [
            "social security", "disability", "ssi",
            "supplemental security", "child welfare", "foster care",
            "adoption", "poverty", "welfare", "tanf",
            "social services", "community service", "charitable",
            "nonprofit", "child care", "childcare", "elder care",
            "aging", "senior", "meals on wheels", "low-income",
            "low income", "disadvantaged", "underserved",
            "vulnerable", "family services",
        ],
    },
    {
        "name": "Veterans Affairs",
        "slug": "veterans-affairs",
        "description": "VA benefits, veteran healthcare, GI Bill, veteran employment.",
        "keywords": [
            "veteran", "veterans affairs", "va hospital", "va benefit",
            "gi bill", "veteran healthcare", "ptsd", "wounded warrior",
            "veteran employment", "military family", "gold star",
            "memorial", "honors", "burial", "arlington",
            "service-connected", "disabled veteran",
        ],
    },
]
