# Generated by Django 4.2.29 on 2026-03-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="changelog",
            new_name="changelog_c_created_64c4f2_idx",
            old_name="changelog_c_created_2a3b4c_idx",
        ),
        migrations.RenameIndex(
            model_name="changelog",
            new_name="changelog_c_bill_id_2b8ac2_idx",
            old_name="changelog_c_bill_id_5d6e7f_idx",
        ),
        migrations.RenameIndex(
            model_name="changelog",
            new_name="changelog_c_change__7f1933_idx",
            old_name="changelog_c_change_8f9a0b_idx",
        ),
    ]
