"""Convert PostgreSQL ChangeLog storage to monthly UTC range partitions.

PostgreSQL requires every partitioned-table primary key to contain the
partition key.  ChangeLog therefore uses ``(id, created_at)`` physically while
continuing to use a single, global identity sequence for normal Django writes.
No model may hold a ForeignKey to ChangeLog; the forward migration fails before
the swap if one has been added.
"""

from datetime import date, datetime, timezone
from typing import ClassVar

from django.db import migrations

TABLE = "changelog_changelog"
FORWARD_SHADOW_TABLE = "changelog_changelog_partitioned"
REVERSE_SHADOW_TABLE = "changelog_changelog_unpartitioned"
FORWARD_OLD_TABLE = "changelog_changelog_pre_partition"
REVERSE_OLD_TABLE = "changelog_changelog_pre_unpartition"
PARTITION_HORIZON_MONTHS = 12

INDEXES = (
    ("changelog_c_bill_id_2b8ac2_idx", '"bill_id"'),
    ("changelog_c_change__7f1933_idx", '"change_type"'),
    ("changelog_c_created_64c4f2_idx", '"created_at" DESC'),
    ("changelog_changelog_bill_id_a3ee17ab", '"bill_id"'),
    ("changelog_changelog_change_type_f10a7310", '"change_type"'),
    (
        "changelog_changelog_change_type_f10a7310_like",
        '"change_type" varchar_pattern_ops',
    ),
    ("changelog_changelog_contract_id_da17a066", '"contract_id"'),
    ("changelog_changelog_created_at_fb264109", '"created_at"'),
    ("changelog_changelog_document_id_29ce49b9", '"document_id"'),
    ("changelog_created_bill_idx", '"created_at" DESC, "bill_id"'),
)


def _month_start(value):
    return date(value.year, value.month, 1)


def _next_month(value):
    if value.month == 12:
        return date(value.year + 1, 1, 1)
    return date(value.year, value.month + 1, 1)


def _add_months(value, count):
    for _ in range(count):
        value = _next_month(value)
    return value


def _months_inclusive(first, last):
    current = _month_start(first)
    while current <= last:
        yield current
        current = _next_month(current)


def _utc_partition_bound(value):
    return datetime(value.year, value.month, 1, tzinfo=timezone.utc).strftime(
        "TIMESTAMPTZ '%Y-%m-%d %H:%M:%S+00'"
    )


def _partition_name(value):
    return f"{TABLE}_{value.year:04d}_{value.month:02d}"


def _table_kind(cursor, table):
    cursor.execute("SELECT relkind FROM pg_class WHERE oid = to_regclass(%s)", [table])
    row = cursor.fetchone()
    return row[0] if row else None


def _assert_no_inbound_foreign_keys(cursor):
    cursor.execute(
        "SELECT conrelid::regclass::text, conname "
        "FROM pg_constraint "
        "WHERE contype = 'f' AND confrelid = to_regclass(%s) "
        "ORDER BY conrelid::regclass::text, conname",
        [TABLE],
    )
    foreign_keys = cursor.fetchall()
    if foreign_keys:
        rendered = ", ".join(f"{table}.{name}" for table, name in foreign_keys)
        raise RuntimeError(
            "Cannot partition changelog_changelog while inbound foreign keys exist: "
            f"{rendered}. PostgreSQL requires the partition key in the referenced "
            "unique constraint."
        )


def _create_table(cursor, table, *, partitioned):
    identity_sequence = f"{table}_id_seq"
    primary_key = f"{table}_pkey"
    partition_clause = ' PARTITION BY RANGE ("created_at")' if partitioned else ""
    cursor.execute(
        f'CREATE TABLE "{table}" ('
        f'"id" bigint GENERATED BY DEFAULT AS IDENTITY '
        f'(SEQUENCE NAME "{identity_sequence}") NOT NULL, '
        '"bill_id" bigint NOT NULL, '
        '"document_id" bigint NULL, '
        '"contract_id" bigint NULL, '
        '"change_type" varchar(50) NOT NULL, '
        '"old_value" jsonb NULL, '
        '"new_value" jsonb NOT NULL, '
        '"created_at" timestamp with time zone NOT NULL, '
        f'CONSTRAINT "{primary_key}" PRIMARY KEY ("id", "created_at"), '
        'CONSTRAINT "changelog_changelog_bill_id_a3ee17ab_fk_legislation_bill_id" '
        'FOREIGN KEY ("bill_id") REFERENCES "legislation_bill" ("id") '
        "DEFERRABLE INITIALLY DEFERRED, "
        'CONSTRAINT "changelog_changelog_document_id_29ce49b9_fk_legislati" '
        'FOREIGN KEY ("document_id") REFERENCES "legislation_billdocument" ("id") '
        "DEFERRABLE INITIALLY DEFERRED, "
        'CONSTRAINT "changelog_changelog_contract_id_da17a066_fk_legislati" '
        'FOREIGN KEY ("contract_id") REFERENCES "legislation_billcontract" ("id") '
        "DEFERRABLE INITIALLY DEFERRED"
        f"){partition_clause}"
    )


def _create_parent_indexes(cursor):
    for name, columns in INDEXES:
        cursor.execute(f'CREATE INDEX "{name}" ON "{TABLE}" ({columns})')


def _set_identity_sequence(cursor, table):
    cursor.execute(f'SELECT MAX("id") FROM "{table}"')
    maximum_id = cursor.fetchone()[0]
    if maximum_id is None:
        cursor.execute(f'ALTER TABLE "{table}" ALTER COLUMN "id" RESTART WITH 1')
        return
    cursor.execute("SELECT pg_get_serial_sequence(%s, 'id')", [table])
    sequence = cursor.fetchone()[0]
    cursor.execute("SELECT setval(%s::regclass, %s, true)", [sequence, maximum_id])


def _copy_rows(cursor, source, destination):
    cursor.execute(
        f'INSERT INTO "{destination}" ('
        '"id", "bill_id", "document_id", "contract_id", "change_type", '
        '"old_value", "new_value", "created_at") '
        "OVERRIDING SYSTEM VALUE "
        f'SELECT "id", "bill_id", "document_id", "contract_id", '
        '"change_type", "old_value", "new_value", "created_at" '
        f'FROM "{source}"'
    )


def _flush_deferred_foreign_keys(cursor):
    """Check copied rows before creating inherited partition indexes.

    The original constraints are ``DEFERRABLE INITIALLY DEFERRED``. PostgreSQL
    refuses to build a partitioned index while a child still has pending
    trigger events from the bulk copy.
    """
    cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def _rename_identity_and_primary_key(cursor, shadow_table):
    cursor.execute(
        f'ALTER TABLE "{TABLE}" RENAME CONSTRAINT '
        f'"{shadow_table}_pkey" TO "{TABLE}_pkey"'
    )
    cursor.execute(f'ALTER SEQUENCE "{shadow_table}_id_seq" RENAME TO "{TABLE}_id_seq"')


def _partition_months(cursor):
    cursor.execute(f'SELECT MIN("created_at"), MAX("created_at") FROM "{TABLE}"')
    minimum, maximum = cursor.fetchone()
    current_month = _month_start(datetime.now(timezone.utc))
    first_month = _month_start(minimum) if minimum else current_month
    last_month = max(
        _month_start(maximum) if maximum else current_month,
        _add_months(current_month, PARTITION_HORIZON_MONTHS),
    )
    return _months_inclusive(first_month, last_month)


def _create_monthly_partitions(cursor, parent):
    for month in _partition_months(cursor):
        next_month = _next_month(month)
        cursor.execute(
            f'CREATE TABLE "{_partition_name(month)}" '
            f'PARTITION OF "{parent}" '
            f"FOR VALUES FROM ({_utc_partition_bound(month)}) "
            f"TO ({_utc_partition_bound(next_month)})"
        )


def _lock_source_table(cursor):
    # A bounded maintenance window is required. Failing instead of waiting
    # indefinitely avoids turning a long-running feed read into an outage.
    cursor.execute("SET LOCAL lock_timeout = '5s'")
    cursor.execute(f'LOCK TABLE "{TABLE}" IN ACCESS EXCLUSIVE MODE')


def partition_changelog(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        table_kind = _table_kind(cursor, TABLE)
        if table_kind == "p":
            return
        if table_kind != "r":
            raise RuntimeError(
                f"Expected regular PostgreSQL table {TABLE}, found {table_kind!r}"
            )

        _lock_source_table(cursor)
        _assert_no_inbound_foreign_keys(cursor)
        _create_table(cursor, FORWARD_SHADOW_TABLE, partitioned=True)
        _create_monthly_partitions(cursor, FORWARD_SHADOW_TABLE)
        _copy_rows(cursor, TABLE, FORWARD_SHADOW_TABLE)
        _set_identity_sequence(cursor, FORWARD_SHADOW_TABLE)
        _flush_deferred_foreign_keys(cursor)
        cursor.execute(f'ALTER TABLE "{TABLE}" RENAME TO "{FORWARD_OLD_TABLE}"')
        cursor.execute(f'ALTER TABLE "{FORWARD_SHADOW_TABLE}" RENAME TO "{TABLE}"')
        cursor.execute(f'DROP TABLE "{FORWARD_OLD_TABLE}"')
        _rename_identity_and_primary_key(cursor, FORWARD_SHADOW_TABLE)
        _create_parent_indexes(cursor)


def unpartition_changelog(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        table_kind = _table_kind(cursor, TABLE)
        if table_kind == "r":
            return
        if table_kind != "p":
            raise RuntimeError(
                f"Expected partitioned PostgreSQL table {TABLE}, found {table_kind!r}"
            )

        _lock_source_table(cursor)
        _create_table(cursor, REVERSE_SHADOW_TABLE, partitioned=False)
        _copy_rows(cursor, TABLE, REVERSE_SHADOW_TABLE)
        _set_identity_sequence(cursor, REVERSE_SHADOW_TABLE)
        _flush_deferred_foreign_keys(cursor)
        cursor.execute(f'ALTER TABLE "{TABLE}" RENAME TO "{REVERSE_OLD_TABLE}"')
        cursor.execute(f'ALTER TABLE "{REVERSE_SHADOW_TABLE}" RENAME TO "{TABLE}"')
        cursor.execute(f'DROP TABLE "{REVERSE_OLD_TABLE}"')
        _rename_identity_and_primary_key(cursor, REVERSE_SHADOW_TABLE)
        _create_parent_indexes(cursor)


class Migration(migrations.Migration):
    atomic = True

    dependencies: ClassVar = [
        (
            "changelog",
            "0002_rename_changelog_c_created_2a3b4c_idx_changelog_c_created_64c4f2_idx_and_more",
        ),
    ]

    operations: ClassVar = [
        migrations.RunPython(partition_changelog, unpartition_changelog),
    ]
