# Generated by Django 4.2.29 on 2026-03-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("congress", "0002_vote_voterecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="representative",
            new_name="congress_re_chamber_211ef4_idx",
            old_name="congress_rep_chamber_7b2a0b_idx",
        ),
        migrations.RenameIndex(
            model_name="representative",
            new_name="congress_re_state_744ffe_idx",
            old_name="congress_rep_state_2c8b0d_idx",
        ),
        migrations.RenameIndex(
            model_name="voterecord",
            new_name="congress_vo_vote_id_d7e75a_idx",
            old_name="congress_vot_vote_id_1a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="voterecord",
            new_name="congress_vo_represe_d3f660_idx",
            old_name="congress_vot_represe_4d5e6f_idx",
        ),
    ]
