# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


def remove_duplicate_vote_records(apps, schema_editor):
    VoteRecord = apps.get_model("congress", "VoteRecord")
    seen = set()
    for record in VoteRecord.objects.order_by("-id").iterator():
        key = (record.vote_id, record.representative_id)
        if key in seen:
            record.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        (
            "congress",
            "0003_rename_congress_rep_chamber_7b2a0b_idx_congress_re_chamber_211ef4_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_vote_records,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="voterecord",
            constraint=models.UniqueConstraint(
                fields=("vote", "representative"),
                name="congress_voterecord_vote_representative_uniq",
            ),
        ),
    ]
