# Generated by Django 5.2.17 on 2026-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("congress", "0008_representative_insight_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemembership",
            name="source_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="CommitteeRosterSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("congress", models.PositiveSmallIntegerField()),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("senate", "Senate"),
                            ("joint", "Joint"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_url", models.URLField(max_length=1024)),
                ("source_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField()),
                ("assignment_count", models.PositiveIntegerField()),
                ("representative_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "congress_committeerostersnapshot",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("congress", "chamber"),
                        name="congress_committee_roster_scope_uniq",
                    )
                ],
            },
        ),
    ]
