# Generated by Django 5.2.17 on 2026-08-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0009_committee_roster_snapshots'),
        ('legislation', '0009_billsearchchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['congress', 'chamber', 'source_updated_at'], name='congress_vote_source_idx'),
        ),
    ]
